# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](rose)\
$os\
$username\
[](bg:peach fg:rose)\
$directory\
[](fg:peach bg:sapphire)\
$docker_context\
[](fg:sapphire bg:lavender)\
$time\
[ ](fg:lavender)\
$line_break$character"""

# Disable the blank line at the start of the prompt
add_newline = true

# Set custom color palette
palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rose = '#f5e0dc'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
sapphire = '#74c7ec'
lavender = '#b4befe'
base = '#1e1e2e'

[os]
disabled = false
style = "bg:rose fg:base"

[username]
show_always = true
style_user = "bg:rose fg:base"
format = '[$user]($style)'

[directory]
style = "bg:peach fg:base"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = "󱑢 "
"Music" = "󰝚 "
"Pictures" = "󰄄 "

[nodejs]
disabled = true

[rust]
disabled = true

[golang]
disabled = true

[php]
disabled = true

[java]
disabled = true

[kotlin]
disabled = true

[haskell]
disabled = true

[python]
disabled = true

[c]
disabled = true

[elixir]
disabled = true

[elm]
disabled = true

[julia]
disabled = true

[nim]
disabled = true

[scala]
disabled = true

[docker_context]
symbol = ""
style = "bg:sapphire fg:base"
format = '[[ $symbol $context ]($style)]($style)'

[character]
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'
